### PR TITLE
Remove img from blinking Instagram service declarations

### PR DESCRIPTION
**Pull request by afisher3578**
Created a filter to remove images that were causing blinking

### CODE REVIEW

**Review by clementbiron — APPROVED** [review]

**Review by martinratinaud — CHANGES_REQUESTED** [review]
It seems weird to me that the history file has changes instead of only additions.

Shouldn't there be a whole new entry for Terms Of Service?

**Comment by afisher3578** [comment]
@martinratinaud Thank you for pointing that out with the history file. I believe I must have not updated the whole history entry. I think this last commit should fix it here

**Comment by martinratinaud** [comment]
From what I see you fixed 2 services

- Terms of use
- Deverloper terms

There should thus be 2 new entries in the history, one for each of those documents.
Existing history should remain unchanged

Here, existing history for Terms of Service has changed with a weird `"validUntil": "2028-10-11T04:33:26+04:00"` which is definitely wrong

New entry in `Terms of Service` history should be

```
{
      "fetch": "https://help.instagram.com/581066165581870",
      "select": [
        "div[role=\"main\"]"
      ],
      "remove": [
        "div[aria-label=\"Copy Link\"]",
        "[id='Related Articles']",
        "fieldset"
      ],
      "filter": [
        "cleanUrls",
        "removeTrackingIDsE"
      ],
      "executeClientScripts": true,
      "validUntil": "Te date when it stopped working"
    }
```

**Comment by martinratinaud** [comment]
@afisher3578 I made a commit with the desired changes on the history file. Can you please check it as I may have not be clear in my previous asking

**Review by martinratinaud — APPROVED** [review]

**Pull request merged**
