### PR TITLE
Add Facebook community guidelines declarations

### PR DESCRIPTION
**Pull request by afisher3578**
Start tracking community guidelines, based off of france-elections declarations

### CODE REVIEW

**Comment by clementbiron** [comment]
I'm going on holiday, @martinratinaud can you handle it please ?

**Comment by martinratinaud** [comment]
@afisher3578 as discussed, you can't use selectors such as `._9nxl` as they will break on each change of the document

You can try to use `body > div > section` for example

And for the subsequent pages, maybe a range between first `h4` and `button`

**Comment by afisher3578** [comment]
@martinratinaud I updated these selectors by using the contrib tool. These selectors worked well in the tool and when ran locally. But when tested locally, I received an InaccessibleContentError so I am not sure if this fix is working

**Comment by martinratinaud** [comment]
@afisher3578 This is because there are some h4 in the header and the range selector end up empty.

I made a new version that works better.

I left the Read more/Read less button on purpose as I did not find a clever selector. The only one I found was `#policy-details a` and I felt it was too broad.

**Review by martinratinaud — APPROVED** [review]
I also reordered the selectors to be more readable

**Pull request merged**
