### PR TITLE
Fix Quora Community Guidelines

### PR DESCRIPTION
**Pull request by smmkolesnikov**

### CODE REVIEW

**Comment by smmkolesnikov** [comment]
Hi @OpenTermsArchive/core! For some reason the engine cannot reach Quora CG here (error 403), though locally it works well and I managed to record a version on my device. Client scripts are already on in the declaration. Do you know how can I fix this?

**Comment by MattiSG** [comment]
Unfortunately, the most likely in this case is that Quora is using a bot blocker that prevents accessing their data through the GitHub continuous integration servers.
I see however that the production servers you are using seem to [be able](https://github.com/OpenTermsArchive/pga-versions/commit/07aa3a52ca0bbd64a2f2d52da8a41b901d32c991) to access Quora's terms.
In this case, as administrator of this repository, you could bypass branch protections and force the merge even though the automated checks failed, in the assumption that the data will be collected properly from the production server 🙂

**Comment by MattiSG** [comment]
@smmkolesnikov were you able to deploy these changes? Do you need any help? 🙂

**Comment by smmkolesnikov** [comment]
Hi @MattiSG! Unfortunately not :( 
I tagged you in a separate pull request where I tried it again but could not force the merge unfortunately  
https://github.com/OpenTermsArchive/pga-declarations/pull/298

**Pull request closed without merging**
