### PR TITLE
Fix Facebook blinking and remove bottom menus

### PR DESCRIPTION
**Pull request by afisher3578**
Added new selectors to remove bottom menu from blinking pages. Also created a new filter to remove the contact image from ToS

### CODE REVIEW

**Review by clementbiron — APPROVED** [review]

**Review by martinratinaud — CHANGES_REQUESTED** [review]
If a declaration is changed, there should be a new entry in the history file. Unless I'm mistaking, the history entry is changed here

**Comment by martinratinaud** [comment]
@afisher3578, looking at the [diff files](https://github.com/OpenTermsArchive/pga-declarations/pull/48/files)

There are several problems
- the history file has been changed instead of amended with new entries
- there is a "end of file line" problem, suggesting you have not used the `npm run lint` command
- the new selectors are too specific and will break at the next update

Please stop working on this and I will modify the PR myself after having adapted the contribution tool to handle the "blink fix" feature.

One question though, have you checked manually the `validUntil` dates for each document? Is it safe for me to use them?

**Comment by afisher3578** [comment]
Hey @martinratinaud that is strange the history files are messed up because I worked on them the same as I always do and ran `npm run lint` but thank you for looking at this 💪

I also checked again the `validUntil` for the documents and for and the correct values are:

Terms of Service: `"validUntil": "2022-07-12T04:33:26+04:00"`
Commercial Terms: `"validUntil": "2022-09-28T04:33:26+04:00"`
Live Policy: `"validUntil": "2022-08-18T04:33:26+04:00"`

**Comment by martinratinaud** [comment]
I will close this PR as I created 3 new directly from the Contribution tool

- https://github.com/OpenTermsArchive/pga-declarations/pull/57
- https://github.com/OpenTermsArchive/pga-declarations/pull/59
- https://github.com/OpenTermsArchive/pga-declarations/pull/60

@afisher3578 please let me know by email when you can be available for me to run you through the new process

**Pull request closed without merging**
