### PR TITLE
Update TikTok URLs to fetch English

### PR DESCRIPTION
**Pull request by afisher3578**
I tried to make these changes with the contrib tool in these PRs #65 #66 but the validate modified declarations check failed each time, so I tried it manually with this pull request but getting the same result. 

This was linted and passed tests when ran locally, so I am not sure why this is not passing this check.

### CODE REVIEW

**Comment by martinratinaud** [comment]
@afisher3578 the checkes are failing for multiple reasons here:

- Trackers Policy URL goes to 404 https://www.tiktok.com/legal/tiktok-website-cookies-policy?lang=en
- it seems the selector is wrong `The provided selector "[data-testid="policy-card"]" has no match` for Privacy Policy

**Comment by afisher3578** [comment]
@martinratinaud That Privacy Policy selector was working locally and with the GUI, but now I tried a new one with startBefore and endBefore

The Trackers Policy URL seems to still work for me locally so I don't know why its not working here. I added executeClientScripts but I don't think that did anything

**Comment by martinratinaud** [comment]
@afisher3578 I made a commit that fixes the Privacy Policy.

Unfortunately, I have no solution for the Trackers Policy that gives a 404. Could it be [this url](https://www.tiktok.com/legal/cookie-policy?lang=en) instead?

**Comment by afisher3578** [comment]
Hi @martinratinaud the URL that you linked to seems to be an old Trackers Policy. The new one was updated September 16th and the other one has not be changed since 2020. I will need to look into other ways to access the policy.

**Pull request closed without merging**
