### PR TITLE
Update URL for English language, and fix selectors

### PR DESCRIPTION
**Pull request by afisher3578**
Fix for issue #27 

- Privacy Policy was able to fetch English language with this fix
- Terms of Service and In-App Purchases Policy are still only fetching German language content. 

Is there a solution to this that can be found by editing the declaration files? I remember @MattiSG mentioning this could have to do with the server location in Germany, but I wanted to see if this can be fixed within the declaration file.

### CODE REVIEW

**Review by clementbiron — APPROVED** [review]
As I understand it, the language of the Terms of Service and In-App Purchases Policy are set in a cookie by the value of `default_lang` and we have no way to force this value.

@Ndpnt do you have any ideas ?

**Comment by Ndpnt** [comment]
It seems that using theses URLs make things working:
- `https://www.tiktok.com/legal/terms-of-service-eea?lang=en&selection=true`
- `https://www.tiktok.com/legal/virtual-items-eea?lang=en&selection=true`

**Comment by afisher3578** [comment]
@Ndpnt Thank you for the recommendation, these URLs worked for me also when ran locally

**Review by clementbiron — APPROVED** [review]

**Comment by martinratinaud** [comment]
@afisher3578 the history file is wrong and the linting appears also to have problems.

I will handle that through the contribution tool and thus take care of this PR

**Comment by afisher3578** [comment]
Fixed with #52  #67

**Comment by clementbiron** [comment]
I'm going on holiday, @martinratinaud can you handle it please ?

**Pull request closed without merging**
